#!/usr/bin/env bash
# Configures a new Ubuntu server with a HAProxy load balancer

sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.8
sudo apt-get -y update
sudo apt-get -y install haproxy=1.8.\*

sudo sed -i '/errorfile 504/a listen thelaura' /etc/haproxy/haproxy.cfg
sudo sed -i '/listen thelaura/a         bind :80' /etc/haproxy/haproxy.cfg
sudo sed -i '/bind :80/a         mode http' /etc/haproxy/haproxy.cfg
sudo sed -i '/mode http/a         server 2154-web-01 104.196.50.234:80 check' /etc/haproxy/haproxy.cfg
sudo sed -i '/server 2154-web-01 104.196.50.234:80 check/a         server 2154-web-02 35.237.11.53:80 check' /etc/haproxy/haproxy.cfg

sudo sed -i '/#EXTRAOPTS="-de -m 16"/a ENABLED=1' /etc/default/haproxy

sudo service haproxy start
